### PR TITLE
add files index.html, style.css [#160126704]

### PR DESCRIPTION
**Pull request by Luleherll**
This pull request will merge the develop branch  which contain the index.html and style.css files to master branch.

### CODE REVIEW

**Comment by ekumamait** [comment]
Nice work

**Comment by ekumamait** [comment]
Nice work

**Comment by joelethan** [comment]
This is great work, well done Lule

**Comment by mulondo** [comment]
its fine, good work

**Comment by edmondsylar** [comment]
Woow bro this is some good stuff here

**Pull request merged**
